# -*- coding: utf-8 -*-
"""Neural_Network_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gul0PiieCgnoGT9nL-xqsyAXt9RnFBYs

# Dataset Description

This project uses the Iris Flower Dataset, one of the most well-known datasets in machine learning.

Source:
https://gist.githubusercontent.com/Thanatoz-1/9e7fdfb8189f0cdf5d73a494e4a6392a/raw/aaecbd14aeaa468cd749528f291aa8a30c2ea09e/iris_dataset.csv
Features:

Each row in the dataset represents a flower with the following measurements:

sepal_length – Length of the sepal (cm)
sepal_width – Width of the sepal (cm)
petal_length – Length of the petal (cm)
petal_width – Width of the petal (cm)
Target Classes:

The model predicts one of three flower species:

Setosa
Versicolor
Virginica
Dataset Size:
150 samples total
50 samples per class

# Installation

Make sure you have Python installed (preferably Python 3.8+), then install the required libraries:
"""

pip install torch pandas numpy scikit-learn matplotlib

"""# Importing the Necessary Libraries"""

# Commented out IPython magic to ensure Python compatibility.
# to work with dataframes
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import torch

"""# Model Architecture

This project uses a simple feedforward neural network (ANN):

Input layer: 4 neurons (features)

Hidden layers: Fully connected layers with activation functions

Output layer: 3 neurons (one for each class)
"""

class Model(nn.Module):
  # input layer --> hidden layer --> ouput layer


  def __init__(self, input_features=4, h1=8, h2=9, out_features=3):
    super().__init__()
    self.fc1 = nn.Linear(input_features, h1)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)

    return x

torch.cuda.manual_seed_all(41)
model = Model()

"""# Load the dataset"""

url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
my_df = pd.read_csv( url)

my_df

"""# Converting Categorical Labels to Numerical Values

The variety column in the dataset contains text labels (flower names).
Machine learning models cannot work directly with text, so we convert them into numerical values.
"""

my_df['variety'] = my_df['variety'].replace('Setosa', 0.0)
my_df['variety'] = my_df['variety'].replace('Virginica', 1.0)
my_df['variety'] = my_df['variety'].replace('Versicolor', 2.0)

my_df.head()

X = my_df.drop('variety', axis=1)
y = my_df['variety']

X

y

"""# Split the data

Training set --> used to train the model

Testing set --> used to evaluate how well the model performs on unseen data
"""

X = X.values
y = y.values

X_train, X_test, y_trian, y_test = train_test_split(X, y, test_size=0.2, random_state=41)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

le = LabelEncoder()

y_trian = torch.LongTensor(le.fit_transform(y_trian))
y_test = torch.LongTensor(le.transform(y_test))

crtrion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

model.parameters

# Train the model
epochs = 100

losses =  []

for i in range(epochs):
  y_pred = model.forward(X_train)
  loss = crtrion(y_pred, y_trian)

  losses.append(loss.detach().numpy())

  if i % 10 == 0:
    print(f'Epoch: {i} Loss: {loss}')
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

"""# Insights from the Training Loss Curve"""

plt.plot(range(epochs), losses)
plt.ylabel('loss/error')
plt.xlabel('epoch')
plt.show()

"""Overall, this is a healthy training curve   your model is learning properly and approaching convergence without instability."""

with torch.no_grad():
  y_eval = model.forward(X_test)
  loss = crtrion(y_eval, y_test)

loss

correct = 0

with torch.no_grad():
    for i, data in enumerate(X_test):
        y_val = model.forward(data)

        if y_test[i] == 0:
            x = 'Setosa'
        elif y_test[i] == 1:
            x = 'Versicolor'
        else:
            x = 'Virginica'

        # Will tell us what type of flower the network thinks it is
        print(f'{i+1}.) {str(y_val)} \t {y_test[i]} \t {y_val.argmax().item()}')

        # Correct or not
        if y_val.argmax().item() == y_test[i]:
            correct += 1

print(f'We got {correct} correct!')

new_iris = torch.tensor([4.7, 3.2, 1.3, 0.2], dtype=torch.float32)

with torch.no_grad():
  print(model(new_iris))

with torch.no_grad():
  print(model(new_iris))

newer_iris = torch.tensor([5.0, 3.6, 1.4, 0.2	], dtype=torch.float32)

with torch.no_grad():
  print(model(newer_iris))

newer_iris2 = torch.tensor([4.6, 3.1, 1.5, 0.2	], dtype=torch.float32)

with torch.no_grad():
  print(model(newer_iris2))

# Save the NN Model
torch.save(model.state_dict(), 'iris_nn.pt')

# Load the Saved Model

new_model = Model()
new_model.load_state_dict(torch.load('iris_nn.pt'))

# Make sure it loaded correctly
new_model.eval()

"""# Project Summary

This project focuses on building a machine learning classification model using PyTorch to identify different species of iris flowers.

The model is trained on the Iris dataset, which contains measurements of flower features such as sepal length, sepal width, petal length, and petal width. These features are used to classify flowers into three categories: Setosa, Versicolor, and Virginica.

**During the process:**

The dataset was preprocessed by converting categorical labels into numerical values
The data was split into training and testing sets
A feedforward neural network was designed and trained over multiple epochs
Model performance was evaluated using test data

The training results show a steady decrease in loss, indicating that the model successfully learns patterns from the data and improves its predictions over time.
"""